<script setup lang="ts">
import type { TierStatusResponse, TierScenario } from '~/utils/mockTierApi'
import BmStatusBadge from '~/components/prototypes/BmStatusBadge.vue'
import RevIcon from '~/components/RevIcon.vue'
defineProps<{ seller: TierStatusResponse; scenario?: TierScenario }>()
const formatEur = (amount: number) => `€${amount.toLocaleString('en-GB', { maximumFractionDigits: 0 })}`
</script>
<template>
  <div id="concept-4-daily-payouts" class="max-w-6xl">
    <div class="flex items-end justify-between mb-6"><div><h1 class="text-3xl font-bold text-bm-text-hi">Daily payouts</h1><p class="text-sm text-bm-text-mid mt-2">Get eligible payouts sooner through BackFunds.</p></div><span class="text-xs font-semibold rounded-full bg-green-50 text-green-700 px-3 py-1.5">Active</span></div>
    <div class="rounded-bm overflow-hidden bg-bm-green-900 text-white shadow-sm mb-6"><div class="p-7"><div class="flex items-start justify-between gap-5"><div><p class="text-xs font-semibold uppercase tracking-widest text-green-300 mb-3">BackFunds · Powered by Storfund</p><h2 class="text-2xl font-semibold">Active daily advances</h2><p class="text-sm text-gray-300 mt-2">Your eligible payouts are being advanced sooner.</p></div><span class="rounded-full bg-green-400/15 border border-green-300/30 px-3 py-1 text-xs font-semibold text-green-200">Active</span></div><div class="grid grid-cols-4 gap-6 mt-8"><div><p class="text-xs text-gray-400 mb-2">Today's advance</p><p class="text-2xl font-bold text-green-300">€625</p><p class="text-xs text-gray-400 mt-1">Landing tomorrow</p></div><div><p class="text-xs text-gray-400 mb-2">Advanced this month</p><p class="text-2xl font-bold">€10,625</p><p class="text-xs text-gray-400 mt-1">17 advances</p></div><div><p class="text-xs text-gray-400 mb-2">Fees this month</p><p class="text-2xl font-bold">€617</p><p class="text-xs text-gray-400 mt-1">0.11% daily fee</p></div><div><p class="text-xs text-gray-400 mb-2">Advance rate</p><p class="text-2xl font-bold">80%</p><p class="text-xs text-gray-400 mt-1">of eligible balance</p></div></div></div><div class="flex items-center justify-between border-t border-white/10 bg-bm-green-800 px-7 py-4"><p class="text-xs text-gray-400">No long-term commitment. Pause anytime.</p><button type="button" class="prototype-hotspot text-sm font-semibold text-white underline underline-offset-2">Manage on Storfund <RevIcon name="IconArrowRight" class="ml-1 inline h-3.5 w-3.5" /></button></div></div>
    <div class="card p-6"><div class="flex items-center justify-between mb-5"><div><h2 class="text-lg font-semibold text-bm-text-hi">Upcoming payouts</h2><p class="text-sm text-bm-text-mid mt-1">Payouts sent sooner through BackFunds.</p></div><button type="button" class="prototype-hotspot text-sm font-semibold text-bm-text-hi underline underline-offset-2">View payout history</button></div><div class="overflow-hidden rounded-bm-sm border border-bm-border"><div class="grid grid-cols-[1.2fr_1.1fr_1fr_0.8fr] gap-4 bg-bm-gray-50 px-4 py-3 text-xs font-semibold text-bm-text-mid"><span>Payout date</span><span>Sales period</span><span>Amount</span><span>Status</span></div><div class="grid grid-cols-[1.2fr_1.1fr_1fr_0.8fr] gap-4 items-center border-t border-bm-border px-4 py-4 text-sm"><span class="text-bm-text-mid">11 Aug 2026</span><span class="text-bm-text-mid">08 Aug - 10 Aug</span><span class="font-semibold text-bm-text-hi">€4,250</span><BmStatusBadge label="Paid faster" tone="success" /></div><div class="grid grid-cols-[1.2fr_1.1fr_1fr_0.8fr] gap-4 items-center border-t border-bm-border px-4 py-4 text-sm"><span class="text-bm-text-mid">12 Aug 2026</span><span class="text-bm-text-mid">29 Jul - 05 Aug</span><span class="font-semibold text-bm-text-hi">€13,700</span><BmStatusBadge label="Scheduled" tone="info" /></div></div></div>
  </div>
</template>
